# Minimal example with TensorFlow 2.0
In this notebook we will recreate our machine learning algorithm using TF 2.0.

## Import the relevant libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

## Data generation

In [2]:
observations = 1000

xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10, 10, (observations,1))

generated_inputs = np.column_stack((xs,zs))

noise = np.random.uniform(-1, 1, (observations,1))

generated_targets = 2*xs - 3*zs + 5 + noise

np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)


## Solving with TensorFlow

In [3]:
training_data = np.load('TF_intro.npz')

In [4]:
input_size = 2
output_size = 1

model = tf.keras.Sequential([
                            tf.keras.layers.Dense(output_size)
                            ])

model.compile(optimizer='sgd', loss='mean_squared_error')

model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=1)

Epoch 1/100
32/32 [==============================] - 1s 1ms/step - loss: 39.5750
Epoch 2/100
32/32 [==============================] - 0s 1ms/step - loss: 4.3826
Epoch 3/100
32/32 [==============================] - 0s 1ms/step - loss: 1.4342
Epoch 4/100
32/32 [==============================] - 0s 1ms/step - loss: 0.6495
Epoch 5/100
32/32 [==============================] - 0s 1ms/step - loss: 0.4411
Epoch 6/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3722
Epoch 7/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3626
Epoch 8/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3566
Epoch 9/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3606
Epoch 10/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3612
Epoch 11/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3593
Epoch 12/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3586
Epoch 13/100
32/32 [================

## Extract the weights and bias

In [5]:
model.layers[0].get_weights()

[array([[ 2.0446706],
        [-3.0272892]], dtype=float32),
 array([4.98494], dtype=float32)]

In [6]:
weights = model.layers[0].get_weights()[0]
weights

array([[ 2.0446706],
       [-3.0272892]], dtype=float32)

In [7]:
bias = model.layers[0].get_weights()[1]
bias

array([4.98494], dtype=float32)

## Extract the outputs (make predictions)

In [8]:
model.predict_on_batch(training_data['inputs']).round(1)

array([[ 39.2],
       [ 51.7],
       [ 18.1],
       [ 22.1],
       [ 11.4],
       [ -4.5],
       [-22.1],
       [  6.2],
       [ -1.3],
       [ 16.6],
       [-13.8],
       [-18.4],
       [ 28.9],
       [ -4.9],
       [-10.1],
       [  3.7],
       [ 20.2],
       [ 23.9],
       [-16.4],
       [ -9.6],
       [ 32.6],
       [ 36.6],
       [-33.5],
       [ -3.3],
       [ -2.4],
       [ 14.4],
       [ 47. ],
       [ -3.4],
       [  7.5],
       [ 13.1],
       [ 16.7],
       [ 15.8],
       [ 14.3],
       [ -7.5],
       [ 39.8],
       [ -9.2],
       [ -5.2],
       [ -7.8],
       [ 26.9],
       [ -1.9],
       [ -5.4],
       [-18.2],
       [ -2.2],
       [ 23.3],
       [-37.3],
       [-18.6],
       [ 17.6],
       [  9.1],
       [  1.3],
       [  9.3],
       [ -2.9],
       [  5.8],
       [-17. ],
       [ -0.7],
       [ 23.9],
       [-32.2],
       [-28.8],
       [-10.3],
       [ 20.4],
       [-24.1],
       [ 18.1],
       [ 13.3],
       [

In [9]:
training_data['targets'].round(1)

array([[ 39.1],
       [ 51.1],
       [ 19. ],
       [ 22.5],
       [ 12.3],
       [ -5.3],
       [-21. ],
       [  5.6],
       [ -0.9],
       [ 17.2],
       [-12.8],
       [-18.4],
       [ 29. ],
       [ -5.2],
       [-10.8],
       [  2.7],
       [ 20.4],
       [ 22.9],
       [-15.7],
       [-10.1],
       [ 33.2],
       [ 36.5],
       [-32.2],
       [ -3.7],
       [ -2.8],
       [ 13.3],
       [ 46.7],
       [ -3.3],
       [  7.2],
       [ 13.4],
       [ 15.6],
       [ 15.6],
       [ 13.9],
       [ -7.7],
       [ 38.7],
       [ -9.5],
       [ -5.7],
       [ -7.6],
       [ 26.2],
       [ -2.4],
       [ -5. ],
       [-17.7],
       [ -1.8],
       [ 23.3],
       [-36.7],
       [-17.5],
       [ 17.6],
       [  8.3],
       [  2.3],
       [ 10.1],
       [ -3.4],
       [  6.2],
       [-17.2],
       [  0.1],
       [ 24.2],
       [-31. ],
       [-29.2],
       [ -9.3],
       [ 20.2],
       [-23.4],
       [ 17.3],
       [ 13.9],
       [

## Plotting the data

In [ ]:
plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))
plt.xlabel('outputs')
plt.ylabel('targets')
plt.show()